services:
    sf2security.authenticationfailurehandler:
        class: Loamok\Sf2securityBundle\EventHandler\AuthenticationFailureHandler
        arguments: ["@http_kernel", "@security.http_utils", {}, "@logger"]
        tags:
            - { name: 'monolog.logger', channel: 'security' }
